language: python
sudo: false
python:
  - "3.6"
  - "3.5"
env:
  - REQ='Django>=2.1,<2.2'
  - REQ='Django>=2.0,<2.1'
  - REQ='Django>=1.11,<2.0'
matrix:
install:
  - pip install $REQ
  - python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test -v2 testapp && cd .."

jobs:
  include:
    - stage: style
      env: REQ=none
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check fineforms tests
